version: 2.1

jobs:
  build_and_publish_image:
    docker:
      - image: docker:20.10.3-dind
        auth:
          username: brycefisherfleig
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run: |
          docker build . -t brycefisher/lazy-kaniko:latest # TODO - replace with better tag!
          docker push brycefisher/lazy-kaniko:latest

workflows:
  github_push:
    jobs:
      - build_and_publish_image
