version: 2.1

jobs:
  build_and_publish_image:
    docker:
      - image: docker:20.10.3-dind
    steps:
      - checkout
      - run: |
          apk add --no-cache git curl
          curl -vsSLO https://github.com/stefanwalther/docker-image-tag/releases/download/v0.1.10/docker-image-tag_0.1.10_Linux_x86_64.tar.gz
          tar xvfz docker-image-tag_0.1.10_Linux_x86_64.tar.gz
          ls -lah

workflows:
  github_push:
    jobs:
      - build_and_publish_image
